### ISSUE TITLE
终极同调闪退

### ISSUE THREAD

**Issue by FungJiHsu** [FrierenModForSlayTheSpire/Frieren#1]
不知道是按得太快还是怎么回事
第二层打铜制机械人偶，终极同调后，按出第二张终极同调闪退
以下是LOG最后部分：
16:27:48.358 INFO lang.Class> =L=M=K=>publish playing 破灭之雷魔法+<=K=M=L=
16:27:49.075 INFO basemod.BaseMod> publish on post power apply
16:27:49.078 INFO basemod.BaseMod> powers modified
16:27:50.258 INFO basemod.BaseMod> publish on card use: FrierenMod:Mana
16:27:50.258 INFO lang.Class> =L=M=K=>publish playing 魔力<=K=M=L=
16:27:50.408 INFO basemod.BaseMod> publish on post power apply
16:27:50.408 INFO basemod.BaseMod> powers modified
16:27:51.358 INFO basemod.BaseMod> publish on card use: FrierenMod:Mana
16:27:51.358 INFO lang.Class> =L=M=K=>publish playing 魔力<=K=M=L=
16:27:52.091 INFO basemod.BaseMod> publish on card use: FrierenMod:Mana
16:27:52.091 INFO lang.Class> =L=M=K=>publish playing 魔力<=K=M=L=
16:27:52.758 INFO basemod.BaseMod> publish on card use: FrierenMod:Mana
16:27:52.758 INFO lang.Class> =L=M=K=>publish playing 魔力<=K=M=L=
16:27:52.908 INFO basemod.BaseMod> publish on post power apply
16:27:52.908 INFO basemod.BaseMod> powers modified
16:27:53.492 INFO basemod.BaseMod> publish on card use: FrierenMod:Mana
16:27:53.492 INFO lang.Class> =L=M=K=>publish playing 魔力<=K=M=L=
16:27:53.493 INFO core.CardCrawlGame> Exception occurred in CardCrawlGame render method!
16:27:53.493 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at FrierenMod.cardMods.ManaMod.onUse(ManaMod.java:84) ~[FrierenMod.jar:?]
	at basemod.helpers.CardModifierManager.onUseCard(CardModifierManager.java:209) ~[BaseMod.jar:?]
	at basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.CardModifierPatches$CardModifierOnUseCard.Insert(CardModifierPatches.java:662) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.actions.utility.UseCardAction.<init>(UseCardAction.java:46) ~[?:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1700) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:359) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:183) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
16:27:53.508 INFO core.CardCrawlGame> PAUSE()
16:27:53.508 INFO core.CardCrawlGame> Game shutting down...
16:27:53.508 INFO core.CardCrawlGame> Flushing saves to disk...
16:27:53.509 INFO core.CardCrawlGame> Shutting down controller handler...
16:27:53.509 INFO helpers.FileSaver> Save thread interrupted!
16:27:53.509 INFO core.CardCrawlGame> Shutting down publisher integrations...
16:27:53.509 INFO helpers.FileSaver> Save thread will die now.
16:27:53.513 INFO core.CardCrawlGame> Flushing logs to disk. Clean shutdown successful.
16:27:53.528 INFO extendedui.STSEffekseerManager> Terminated STSEffekseerManager

**Comment by Arkalin** [comment]
感谢，已修复
